GET http://localhost:8080/devops-starter/api/person

###Get Dankess
GET http://localhost:8080/hobbies/api/hobbies
Content-Type: application/json

{"str1": "First Property", "str2": "Second Property"}

###Get All hobbies
GET http://localhost:8080/hobbies/api/hobbies/all
Content-Type: application/json

###Get hobbies %like%
GET http://localhost:8080/hobbies/api/hobbies/bord
Content-Type: application/json

###Get people with hobby
GET http://localhost:8080/hobbies/api/hobbies/people/Tegning
Content-Type: application/json

###Get people count with hobby
GET http://localhost:8080/hobbies/api/hobbies/people/count/Bil
Content-Type: application/json

### create a new hobby
POST http://localhost:8080/hobbies/api/hobbies
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json

{
      "name": "Tanks",
      "wikiLink": "https://en.wikipedia.org/wiki/Tanking",
      "category": "tacos",
      "type": "open fields"
}
### edit a hobby
PUT http://localhost:8080/hobbies/api/hobbies/edit/465
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json

{
"name": "Kampvogn",
"wikiLink": "https://en.wikipedia.org/wiki/Tanking",
"category": "Maskineri",
"type": "Store dejlige åbne marker"
}

### delete a hobby
DELETE http://localhost:8080/hobbies/api/hobbies/delete/453
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json