GET http://localhost:8080/devops-starter/api/person

###
POST http://localhost:8080/hobbies/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}

###
POST https://www.sem3nicki.dk/hobbies/person/
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json

{

}

###
GET http://localhost:8080/hobbies/api/person/all
Content-Type: application/json

###
GET http://localhost:8080/hobbies/api/person/66699666
Content-Type: application/json