GET http://localhost:8080/devops-starter/api/person

###
POST http://localhost:8080/hobbies/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}

###
POST https://www.sem3nicki.dk/hobbies/api/person/
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json

{

}

### Get all persons
GET http://localhost:8080/hobbies/api/person/all
Content-Type: application/json

### Get person by phone number
GET http://localhost:8080/hobbies/api/person/phone/123456
Content-Type: application/json

### Get persons by zipcode
GET http://localhost:8080/hobbies/api/person/zipcode/3700
Content-Type: application/json

### Create new person
POST http://localhost:8080/hobbies/api/person
Content-Type: application/json

{
  "address": {
    "street": "Timigade 10",
    "aditionalInfo": "Tv.",
    "idCITY": {
      "city": "Rønne",
      "zipcode": "3700"
    }
  },
  "firstName": "Tommy",
  "lastName": "Tomsen",
  "age": 67,
  "gender": "MaleFe",
  "email": "tim@tim.com"
}


### Update person
PUT http://localhost:8080/hobbies/api/person/update/8
Content-Type: application/json

{
  "address": {
    "street": "Nickigade 10",
    "aditionalInfo": "Tv.",
    "idCITY": {
      "city": "Nylars",
      "zipcode": "3711"
    }
  },
  "firstName": "Mikkel",
  "lastName": "Otto",
  "age": 22,
  "gender": "FeMale",
  "email": "bimbam@nicemail.com",
  "phones": [
    {
      "phoneNumber": "654321",
      "description": "Mobil",
      "idPERSON": 8
    }
  ],
  "hobbies": [
    {
      "name": "Kraftløftning",
      "wikiLink": "https://en.wikipedia.org/wiki/Powerlifting",
      "category": "Generel",
      "type": "Indendørs"
    }
  ],
  "idAddress": 8

}

### Delete person
DELETE http://localhost:8080/hobbies/api/person/delete/9
Accept: application/json
