GET http://localhost:8080/devops-starter/api/person

###
POST http://localhost:8080/hobbies/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}

###
POST https://www.sem3nicki.dk/hobbies/api/person/
#POST http://localhost:8080/devops-starter/api/person
Content-Type: application/json

{

}

### Get all persons
GET http://localhost:8080/hobbies/api/person/all
Content-Type: application/json

### Get person by phone number
GET http://localhost:8080/hobbies/api/person/phone/66699666
Content-Type: application/json

### Get persons by zipcode
GET http://localhost:8080/hobbies/api/person/zipcode/3700
Content-Type: application/json

### Update person
PUT http://localhost:8080/hobbies/api/person/update/3
Content-Type: application/json

{
  "address": {
    "street": "Testgade 14",
    "aditionalInfo": "Th.",
    "idCITY": {
      "city": "København K",
      "zipcode": "1353"
    }
  },
  "firstName": "Bimbam",
  "lastName": "Karlos",
  "age": 36,
  "gender": "Male",
  "email": "bimbam@nicemail.com",
  "phones": [
    {
      "phoneNumber": "25255878",
      "description": "Mobil",
      "idPERSON": 3
    }
  ],
  "hobbies": [
    {
      "name": "Kraftløftning",
      "wikiLink": "https://en.wikipedia.org/wiki/Powerlifting",
      "category": "Generel",
      "type": "Indendørs"
    }
  ],
  "idAddress": 1

}

### Delete person
DELETE http://localhost:8080/hobbies/api/person/delete/8
Accept: application/json
